### ISSUE TITLE
parallel edges between nodes

### ISSUE THREAD

**Issue by balhoff** [ExposuresProvider/noctua-models#3]
The demo model appears to have many nodes with multiple edges connecting them. Is this intended?

![image](https://user-images.githubusercontent.com/210210/236543606-e2421bcb-d04e-47c4-a2c8-ec88552b971d.png)

**Comment by mam288** [comment]
Yes, this is intended. We are going to curate the models and select the edges that fit the best.

**Comment by balhoff** [comment]
Okay, thanks!
